### ISSUE TITLE
Filled Clay Buckets cannot be removed from AE2's ME Systems

### ISSUE THREAD

**Issue by katubug** [KnightMiner/Ceramics#51] opened 2019-06-02 16:53 UTC
**Describe the bug**
A player reported to me that they couldn't retrieve a Clay Water Bucket from their ME system. I tested this and can replicate. I can neither remove the Clay Water Bucket, nor the Clay Hot Spring Water Bucket from my ME system. Empty and Unfired Buckets do not seem to be affected.

I have reported this to the mod author of AE2 as well: https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/4058

**To Reproduce**
Place a filled clay bucket inside an ME system via terminal
Attempt to retrieve clay bucket from ME system via terminal

**Expected behavior**
I expect the bucket to be pulled from the ME inventory and placeable within player inventory. However, clicking on the bucket does not do anything. Shift+Click does not work, either.

**Environment**
We are running a multiplayer server. I have not tested this in singleplayer.

Minecraft Version: 1.12.2
AE2 Version: appliedenergistics2-rv6-stable-6
Ceramics Version: Ceramics-1.12-1.3.7
Forge Version: forge-1.12.2-14.23.5.2838-universal

**Comment by KnightMiner** [comment] 2019-06-02 20:11
Duplicate of #51.

Definitely not on my side, nothing makes clay buckets different from any other NBT or bucket item, reporter of #51 claimed it's Astral Sorcery causing this.

**Closed as completed by KnightMiner** 2019-06-02 20:11 UTC
Labels: duplicate

**Comment by katubug** [comment] 2019-06-03 04:55
Sorry for the duplicate issue, I should have searched.

**Comment by katubug** [comment] 2019-06-03 04:56
I'm not sure if it's on my end, but isn't this issue #51? I'm on mobile but clicking through your links just takes me back here.

**Comment by KnightMiner** [comment] 2019-06-03 11:52
Sorry, meant #50, but it seems you found it

**Comment by katubug** [comment] 2019-06-03 11:55
Yep, got it! Thank you!
