### ISSUE TITLE
[1.12.2] Null Pointer Crash

### ISSUE THREAD

**Issue by artdude543** [KnightMiner/Ceramics#36] opened 2018-04-14 10:26 UTC
In Regards to https://github.com/Darkosto/SevTech-Ages/issues/1815

Hello, just had this report about a crash with the modpack and the usage of a distillation tower from IE Tech but looking the report given it's just a Null Pointer being thrown from Ceramics.

Crash Report: https://pastebin.com/SqFmHVvf
Version Used:  1.12-1.3.3b

If you need more info the user on how the setup is done/usage then you can chatter on the linked issue 🙂 

Thanks!

**Comment by KnightMiner** [comment] 2018-04-14 15:07
Seen this issue before, but it's impossible for me to fix. It is caused by an area of Forge code which creates a fluid stack then somehow that fluid stack is null a couple lines later. My best guess is some mod is doing something wrong in the fluid fill event, but there is nothing I can do to catch that, you will have to find which mod causes it.

**Comment by KnightMiner** [comment] 2018-11-23 22:27
Closing for lack of update as the linked issue is closed. If I could get minimal steps to reproduce I may be able to address this, but as it stands I have never see this happen and it happens in code I do not control

**Closed as completed by KnightMiner** 2018-11-23 22:27 UTC
Labels: compatibility, can't fix
